### ISSUE TITLE
Padding column

### ISSUE THREAD

**Issue by nomasprime** [kristijanhusak/defx-icons#17]
Is it possible to get a column before the icons?

This would be make it similar to the Denite implementation and avoid display problems with cursor.

**Comment by kristijanhusak** [comment]
Try setting this variable to higher value:
```vimL
let g:defx_icons_column_length = 2
```

**Comment by nomasprime** [comment]
Thanks. I tried setting this before realising it's really a Defx issue.

In the end I'm not using the icon column so I inserted this and set the values to nothing.

**Comment by kristijanhusak** [comment]
Ok, can we close this then?

**Comment by nomasprime** [comment]
Yep. Thanks.
