### ISSUE TITLE
Feature request:  extend vim-devicons instead of duplicating the icons?

### ISSUE THREAD

**Issue by oblitum** [kristijanhusak/defx-icons#2]
With current duplication icon approach, how the plugin is gonna track vim-devicons updates? Wouldn't it be better to depend on vim-devicons and apply colors to the currently tracked but still get new uncolored icons on vim-devicons updates?

**Comment by kristijanhusak** [comment]
The main point of this plugin is to not depend on vim-devicons. Are there any updates in vim-devicons that i'm not aware of?

If you really want to depend on it, you can use https://github.com/mhartington/defx-devicons

**Comment by oblitum** [comment]
@kristijanhusak No updates afaik, just talking in hypothetical terms. About the other plugin, this issue came up because I learned of that one, I didn't switch because no colors there :)

**Comment by oblitum** [comment]
I feel this may be a wontix for the purpose of this one, but I dunno. Feel free do close if you consider it's out of scope.

**Comment by kristijanhusak** [comment]
Yeah it's wontfix. Mhartington created initial version before me that depends on the vim-devicons, but that solution didn't suit me, so i created this one. One dependency less, and the result is the same.
If i miss some updates in vim-devicons, let me know, i'll keep this up to date with it.

**Comment by oblitum** [comment]
OK, sadly for me removing vim-devicons as dep isn't advantage since I use it at other places regardless :-/

**Comment by petobens** [comment]
Hi @kristijanhusak thanks for this great source. Despite not depending on vim-devicons is it possible to read it's configuration? i.e in my vimrc I have the following:
```viml
if !exists('g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols')
    let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
endif
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {'tex': '',
            \ 'bib':'', 'gitcommit': ''}

" Add or override individual specific files
if !exists('g:WebDevIconsUnicodeDecorateFileNodesExactSymbols')
    let g:WebDevIconsUnicodeDecorateFileNodesExactSymbols = {}
endif
let g:WebDevIconsUnicodeDecorateFileNodesExactSymbols = {'.gitconfig': '',
            \ '.gitignore': '', 'bashrc': '', '.bashrc': '',
            \ 'bash_profile': '', '.bash_profile': ''}
if !exists('g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols')
    let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
endif
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['r'] = 'ﳒ'
```
which allows me to add custom glyphs for specific filetypes/file. Can defx-icons read this config and override icons accordingly? Thanks!!

**Comment by kristijanhusak** [comment]
hi @petobens,

no, i don't plan to support anything related to vim-devicons. You can override icons in here also, just check the [plugin file](https://github.com/kristijanhusak/defx-icons/blob/master/plugin/defx_icons.vim).
For example, to override `.gitconfig`, you would have something like this in your vimrc:

```vimL
let g:defx_icons_exact_matches = {'.gitconfig': { 'icon': 'YOURICON', 'color': 'FFFFFF' } }
```
