### ISSUE TITLE
Need more icon for some filetypes

### ISSUE THREAD

**Issue by glepnir** [kristijanhusak/defx-icons#20]
like key file makefile...etc
![image](https://user-images.githubusercontent.com/41671631/89118433-68882a00-d4d8-11ea-9257-30251d628b98.png)

**Comment by kristijanhusak** [comment]
I'm not sure what would we put for `*.key`. Seems like even `vim-devicons` doesn't have an icon for that.

**Comment by glepnir** [comment]
@kristijanhusak  what about `f43d`

**Comment by kristijanhusak** [comment]
@glepnir Yeah that works. I added that and a lot of other icons that are part of vim-devicons.

**Comment by glepnir** [comment]
It works. Maybe add some syntax color will be more beautiful?

**Comment by kristijanhusak** [comment]
I used colors from https://github.com/tiagofumo/vim-nerdtree-syntax-highlight, whatever was set.
Feel free to create a PR with colors that you think will fit.
