### ISSUE TITLE
Icon font display unnormal in Alacritty.

### ISSUE THREAD

**Issue by PangPangPangPangPang** [kristijanhusak/defx-icons#24]
Environment:
MacOS/Alacritty

Kitty+nerdtree: Normal
Kitty+defx: Normal
Alacritty+nerdtree: Normal
Alacritty+defx: Unnormal

![image](https://user-images.githubusercontent.com/8207475/90238840-25737280-de59-11ea-89d0-9dcfb5846edc.png)

**Comment by kristijanhusak** [comment]
Are you sure it's related to icons? Does it happen without the icons column?

**Comment by PangPangPangPangPang** [comment]
> Are you sure it's related to icons? Does it happen without the icons column?

Use default `icon`:
![image](https://user-images.githubusercontent.com/8207475/90243112-df221180-de60-11ea-8e2a-9bded9af9ccf.png)

Config `let g:defx_icons_directory_icon = '+'`:
![image](https://user-images.githubusercontent.com/8207475/90243193-04af1b00-de61-11ea-8d15-424bc3e9ad21.png)

**Comment by kristijanhusak** [comment]
Are you using same font as with kitty? Looks like your font in allacrity doesn't support folder icons.

**Comment by PangPangPangPangPang** [comment]
> Are you using same font as with kitty? Looks like your font in allacrity doesn't support folder icons.

Yes. Only `Alacritty+defx` is abnormal. So weird.
Alacritty+Nerdtree:
![image](https://user-images.githubusercontent.com/8207475/90245452-493cb580-de65-11ea-971b-52ccf12b62ab.png)

**Comment by kristijanhusak** [comment]
Try increasing length setting and see if that helps.

**Comment by PangPangPangPangPang** [comment]
> Try increasing length setting and see if that helps.

It doesn't work.

**Comment by kristijanhusak** [comment]
@PangPangPangPangPang did you figure it out?

**Comment by PangPangPangPangPang** [comment]
> @PangPangPangPangPang did you figure it out?

Update Alacritty and it looks normal now. Lol.

**Comment by kristijanhusak** [comment]
Ok, thanks.
