### ISSUE TITLE
custom file icons

### ISSUE THREAD

**Issue by finviman** [kristijanhusak/defx-icons#25]
does defx-icons extends devicons ? does it support custom file icons?
I config 
```vimscript
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols['xml'] = ''
```
this config doesn't affect display of defx-icons.

**Comment by kristijanhusak** [comment]
Yeah you could do it like this.

```vimL
let g:defx_icons_extensions = {'xml': {'icon': '', 'color': '#FF0000', 'term_color': 4 }}
```

It's a bit more complicated because you need to provide the colors also. You can check what colors are currently used in `plugin/defx_icons.vim`

**Comment by finviman** [comment]
thank you, it works fine.

**Comment by kristijanhusak** [comment]
Great, closing.
