### ISSUE TITLE
the custom color is not applied in neovim

### ISSUE THREAD

**Issue by physical-eng** [kristijanhusak/defx-icons#28]
Hi @kristijanhusak , Thanks your greatful plugins.

Unfortunately, my custom icon color setting is not working in neovim.

I wrote .vimrc and init.vim as below.

``` init.vim 
let g:defx_icons_extensions = {}
let g:defx_icons_extensions['md'] = {'icon': '', 'color': '#0000FF', 'term_color':  67 } "bule
let g:defx_icons_extensions['py'] = {'icon': '', 'color': '#F09F17', 'term_color': 229 } "yellow
```

in vim.

![vim](https://user-images.githubusercontent.com/16160340/107095766-bcd7e200-684c-11eb-97cb-fc534f95f6cb.jpg)

in neovim.

![nvim](https://user-images.githubusercontent.com/16160340/107095345-f6f4b400-684b-11eb-936e-bc492adc1879.jpg)

The default color is applied to test.pyc, but custom one is not.(README.md and test.py)
Please tell me what I made a mistake.

**Comment by kristijanhusak** [comment]
Hi @physical-eng ,

remove the `#` from hex color. You can see how colors are defined here https://github.com/kristijanhusak/defx-icons/blob/master/plugin/defx_icons.vim#L21

**Comment by physical-eng** [comment]
I overlooked it!
Thank you so much!
