### ISSUE TITLE
[bug] ValueError: not enough values to unpack (expectd 2, got 0)

### ISSUE THREAD

**Issue by Freed-Wu** [kristijanhusak/defx-icons#29]
```vim
" File: $XDG_CONFIG_HOME/nvim/test.vim
" OS: linux v5.4.13
" Vi: nvim v0.4.3
" Py: cpython v3.9.0b3
" Term: guake v3.7.0
set runtimepath=$VIMRUNTIME,$GITHUBWORKSPACE/Shougo/defx.nvim,$GITHUBWORKSPACE/kristijanhusak/defx-icons
nnoremap <expr> C defx#do_action('link')
nnoremap <expr> p defx#do_action('paste')
autocmd VimEnter * call defx#custom#option('_', {
				\ 'columns': 'icons:filename',
				\ })
" vi -u $XDG_CONFIG_HOME/nvim/test.vim
```

```vim
Defx
```

`jjjjjCpr2`
![0](https://user-images.githubusercontent.com/32936898/107150026-b6558180-6996-11eb-8618-d1b96a349814.png)

`<CR>`
![1](https://user-images.githubusercontent.com/32936898/107150029-bb1a3580-6996-11eb-8758-1e227d0a567a.png)

the `icons` of `icons:filename` is necessary.
`$GITHUBWORKSPACE/kristijanhusak/defx-icons` is necessary.

i don't determine the bug is derived from defx or this plugin ... the function `defx#do_action('link')` is added recently. before it was added, the bug does not existed.

**Comment by Shougo** [comment]
It is the issue of defx-icons.
Because it does not support `ClipboardAction.LINK`.

https://github.com/kristijanhusak/defx-icons/blob/master/rplugin/python3/defx/column/icons.py#L142
