### ISSUE TITLE
Add directory exact matches

### ISSUE THREAD

**Issue by petobens** [kristijanhusak/defx-icons#3]
Hi is it possible to add something like this: https://github.com/alexanderjeurissen/ranger_devicons/commit/410dec49b59103137d2b0e49fda055d992c65d9b ? Thanks!

**Comment by kristijanhusak** [comment]
Sure, i'll add it. Or if you want it to be done a bit sooner, you can open up a PR.

**Comment by petobens** [comment]
Awesome. Thanks!

**Comment by kristijanhusak** [comment]
I added it. Here's an example:

```vimL
let g:defx_icon_exact_dir_matches = {
                        \ 'node_modules': {'icon': 'NM', 'color': 'FF0000'}
                        \ }
```

**Comment by petobens** [comment]
Thanks! I've noticed that matches must be in lower case. i.e that the following doesn't work:
```viml
let g:defx_icon_exact_dir_matches = {
            \ '.git'     : {'icon': ''},
            \ 'Desktop'  : {'icon': ''},
            \ 'Documents': {'icon': ''},
            \ 'Downloads': {'icon': ''},
            \ 'Dropbox'  : {'icon': ''},
            \ 'Music'    : {'icon': ''},
            \ 'Pictures' : {'icon': ''},
            \ 'Public'   : {'icon': ''},
            \ 'Templates': {'icon': ''},
            \ 'Videos'   : {'icon': ''},
            \ }
```
but using for instance `desktop` instead of `Desktop` does. Can this be changed?

**Comment by kristijanhusak** [comment]
exact file matches behave the same way, that's why i set it up like that. Why is an issue to use lowercase?

**Comment by petobens** [comment]
Because, at least on Linux, you can have both `Desktop` and `desktop` (i.e it's case sensitive). In other words I expect `Desktop` to match `Desktop` and not `desktop`.

**Comment by kristijanhusak** [comment]
Ok, i fixed it. Try now.

**Comment by petobens** [comment]
Working now thanks. Note that files are also case sensitive (i.e you can have both `Foo.py` and `foo.py`) (i believe you only changed this for directories).

**Comment by kristijanhusak** [comment]
Yes, i changed it for directories only. Files were case insensitive from the beginning, because that's how vim-devicons behave https://github.com/ryanoasis/vim-devicons/blob/master/plugin/webdevicons.vim#L640

**Comment by petobens** [comment]
Ok. Feel free to close whenever you deem fit. Thanks again for the quick changes :)
