### ISSUE TITLE
Font icon cannot be displayed, still display default icon

### ISSUE THREAD

**Issue by kevin1121** [kristijanhusak/defx-icons#33]
Nerd fonts font is already installed, run: Defx - columns = the ICONS: text-indent: filename: type
However, ICONS cannot be displayed in directories

![nvim](https://user-images.githubusercontent.com/31364407/146012499-6400d513-3b53-4822-bf02-a79a51cd4cbd.png)

**Comment by kristijanhusak** [comment]
I think you are not running the Defx command correctly. Please give me the exact command that you are running.

**Comment by kevin1121** [comment]
I copied this directly to run:
:Defx -columns=icons:indent:filename:type

Is that wrong? How do I run this command?

**Comment by kevin1121** [comment]
> 我认为您没有正确运行 Defx 命令。请给我您正在运行的确切命令。

**Comment by kevin1121** [comment]
> I think you are not running the Defx command correctly. Please give me the exact command that you are running.

Thank you, rerun will display the icon
