### ISSUE TITLE
Change icons color

### ISSUE THREAD

**Issue by pwntester** [kristijanhusak/defx-icons#6]
Hi,

Is it possible to change the icons colors? In particular, I would like to change the directory/folder one.

Thanks,
A

**Comment by kristijanhusak** [comment]
Hi,

Highlight group used to color the folders is `Directory`. You can override that to get the change.
All the file filetypes can be changed, but not directories specifically. I'll make this available, but until then you can use solution above.

**Comment by pwntester** [comment]
Thanks!

**Comment by kristijanhusak** [comment]
@pwntester i added an option to to this, check this section in readme:
https://github.com/kristijanhusak/defx-icons#override-colors

**Comment by smartding** [comment]
> @pwntester i added an option to to this, check this section in readme:
> https://github.com/kristijanhusak/defx-icons#override-colors

How do I change color for a filetype?

**Comment by kristijanhusak** [comment]
@smartding https://github.com/kristijanhusak/defx-icons/issues/25#issuecomment-691422850

**Comment by smartding** [comment]
> @smartding [#25 (comment)](https://github.com/kristijanhusak/defx-icons/issues/25#issuecomment-691422850)

Thanks, didn't see that issue.
I had to delete the `#` in color to get it working though,
